nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.1.0.cjs
packageExtensions:
  "eslint-import-resolver-vite@*":
    dependencies: # https://github.com/pzmosquito/eslint-import-resolver-vite/pull/22
      "resolve": "*"
      "debug": "*"
