nodeLinker: node-modules

packageExtensions:
  "@vue/runtime-dom@*":
    dependencies:
      "@vue/reactivity": "*"

plugins:
  - checksum: 3427a2f1a2194925e2faf7bafd4fe6d7fd1f61ca178659224ce045249b96147cc8320d4547339f79a099938dd04d45f8f297495e34cd951982c5edede3f3cc25
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v1.0.0/bundles/@yarnpkg/plugin-nolyfill.js"
