name: fe/init
description: fe/init
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: ${{ github.workspace }}/fe/yarn.lock
    - name: install
      run: yarn install --immutable
      working-directory: fe
      shell: bash
