name: fe/init
description: fe/init
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-node@v4
      with: # https://github.com/actions/setup-node/tree/v4
        node-version: latest
        # cache: yarn
        # # https://github.com/actions/setup-node/issues/624#issuecomment-1328681525
        # cache-dependency-path: ${{ github.workspace }}/fe/yarn.lock
        # in favor of https://github.com/actions/cache/blob/a2ed59d39b352305bdd2f628719a53b2cc4f9613/examples.md#node---yarn-2
        # to allow saving cache even jobs failed

    # https://github.com/actions/setup-node/issues/1027
    - run: corepack enable
      shell: bash

    - id: get-yarn-cache-dir
      run: echo "path=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      working-directory: fe
      shell: bash
    - id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.get-yarn-cache-dir.outputs.path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - run: yarn install --immutable
      working-directory: fe
      shell: bash

    # https://github.com/actions/runner/issues/1478
    # https://github.com/actions/setup-node/issues/410#issuecomment-1939482965
    - uses: actions/cache/save@v4
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      with:
        path: ${{ steps.get-yarn-cache-dir.outputs.path }}
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
