name: be/init
description: be/init
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: cs2pr
        coverage: none # https://github.com/shivammathur/setup-php/blob/2.31.1/README.md#disable-coverage
        # https://github.com/shivammathur/setup-php/blob/2.31.1/README.md#jit-configuration
        ini-values: >
          opcache.enable_cli=1, opcache.memory_consumption=256,
          opcache.jit=tracing, opcache.jit_buffer_size=64M
        # https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-windows-2022/aee619eb6d77e86b17a76d458316b41e58a3b677
        # league/flysystem-local@3.28.0 requires ext-fileinfo but it's not enabled by default on windows
        extensions: ${{ runner.os == 'Windows' && 'intl, fileinfo' || '' }}
      env:
        update: 'true' # https://github.com/shivammathur/setup-php/blob/2.31.1/README.md#force-update-setup
    # https://github.com/shivammathur/setup-php/blob/2.31.1/README.md#problem-matchers
    - run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      working-directory: be
      shell: bash

    # https://github.com/shivammathur/setup-php/blob/2.31.1/README.md#cache-composer-dependencies
    # https://github.com/actions/cache/blob/v4.0.2/examples.md#php---composer
    - id: get-composer-cache-dir
      run: echo "path=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      working-directory: be
      shell: bash
    - id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.get-composer-cache-dir.outputs.path }}
        key: ${{ runner.os }}-composer-${{ hashFiles('be/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - run: composer install --no-interaction --no-progress --classmap-authoritative
      working-directory: be
      shell: bash

    # https://github.com/actions/runner/issues/1478
    # https://github.com/actions/setup-node/issues/410#issuecomment-1939482965
    - uses: actions/cache/save@v4
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      with:
        path: ${{ steps.get-composer-cache-dir.outputs.path }}
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
