name: be/init
description: be/init
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: cs2pr
        # https://github.com/shivammathur/setup-php/blob/6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d/README.md#jit-configuration
        coverage: none
        ini-values: opcache.enable_cli=1
        # https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-windows-2022/aee619eb6d77e86b17a76d458316b41e58a3b677
        extensions: fileinfo # league/flysystem-local@3.28.0 requires ext-fileinfo but it's not enabled by default on windows
      env: # https://github.com/shivammathur/setup-php/blob/6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d/README.md#force-update-setup
        update: 'true'
    # https://github.com/shivammathur/setup-php/blob/6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d/README.md#problem-matchers
    - run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      working-directory: be
      shell: bash

    # https://github.com/shivammathur/setup-php/blob/6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d/README.md#cache-composer-dependencies
    # https://github.com/actions/cache/blob/a2ed59d39b352305bdd2f628719a53b2cc4f9613/examples.md#php---composer
    - id: get-composer-cache-dir
      run: echo "path=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      working-directory: be
      shell: bash
    - id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.get-composer-cache-dir.outputs.path }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - run: composer install --no-interaction --no-progress --classmap-authoritative
      working-directory: be
      shell: bash

    # https://github.com/actions/runner/issues/1478
    # https://github.com/actions/setup-node/issues/410#issuecomment-1939482965
    - uses: actions/cache/save@v4
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      with:
        path: ${{ steps.get-composer-cache-dir.outputs.path }}
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
