name: c#/init
description: c#/init
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-dotnet@v4
      with: # https://github.com/actions/setup-dotnet/tree/v4
        dotnet-version: 7
        cache: true
        # https://github.com/actions/setup-node/issues/624#issuecomment-1328681525
        cache-dependency-path: ${{ github.workspace }}/c#/*/packages.lock.json
    - run: dotnet new globaljson --sdk-version 7.0.405
      working-directory: c#
      shell: bash
    - run: dotnet restore
      working-directory: c#
      shell: bash
