name: be/base
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
defaults:
  run:
    working-directory: be
jobs:
  phpstan:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - run: ./vendor/bin/phpstan analyse --error-format=github

  psalm:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - run: ./vendor/bin/psalm --output-format=github

  phpcs:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - id: run
        run: ./vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml .
      - if: always() && steps.run.outcome == 'failure'
        run: cs2pr ./phpcs-report.xml

  # https://github.com/staabm/annotate-pull-request-from-checkstyle
  pint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - id: run
        run: ./vendor/bin/pint --test
      - if: failure() && steps.run.outcome != 'success'
        run: ./vendor/bin/pint --test --format=checkstyle | cs2pr

  php-cs-fixer:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - run: ./vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle . | cs2pr

  phpmd:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/be
      - run: ./vendor/bin/phpmd . github cleancode,codesize,controversial,design,naming,unusedcode --exclude vendor # https://github.com/phpmd/phpmd/issues/506
