name: c#
on:
  push:
    paths: [c#/**]
defaults:
  run:
    working-directory: c#
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        project: [crawler, imagePipeline, shared, tbClient]
      fail-fast: false
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/c#
      - run: dotnet build --no-restore -c Release ${{ matrix.project }}

  ReSharper:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/c#

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/.resharper
            ~/.dotnet/tools
          key: ${{ runner.os }}-resharper
          restore-keys: ${{ runner.os }}-resharper-

      - uses: muno92/resharper_inspectcode@v1
        with:
          version: 2024.*
          minimumReportSeverity: info
          minimumSeverity: warning
          solutionPath: c#/tbm.sln
          cachesHome: ${{ github.workspace }}/.resharper

      # https://github.com/actions/runner/issues/1478
      - uses: actions/cache/save@v4
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ github.workspace }}/.resharper
            ~/.dotnet/tools
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
