# https://stackoverflow.com/questions/75318609/matrix-strategy-over-entire-workflow-in-github-actions/75337311#75337311
name: c#/runs-on
on:
  push:
    paths: [c#/**]
jobs:
  runs-on:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    uses: ./.github/workflows/c#.yml
    with:
      runs-on: ${{ matrix.runs-on }}
