name: fe/base
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
defaults:
  run:
    working-directory: fe
jobs:
  tsc:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fe
      - run: yarn run vue-tsc

  eslint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fe
      - run: yarn run eslint src

  codechecks:
    runs-on: ${{ inputs.runs-on }}
    steps: # contains CVE that triggers Dependabot
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fe
      - run: |
          yarn add -D typecov @codechecks/client
          yarn run codechecks ../.github/codechecks.yml
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
